export const methodDrills = [
 {question:'Ten independent insureds each have the same probability of a claim. You need the probability exactly three claim.',choices:['Binomial count','Geometric waiting count','Hypergeometric count'],answer:0,explanation:'The trial count is fixed, trials are independent, and success probability is constant. Nothing is sampled without replacement.',topicId:'urv-b2-binomial'},
 {question:'Inspect files without replacement from a known collection containing 12 legitimate and 3 fraudulent files. You need the fraud count in five selected files.',choices:['Poisson count','Hypergeometric count','Binomial count'],answer:1,explanation:'The finite population composition is fixed and each removal changes the next-draw probabilities.',topicId:'urv-b5-hypergeometric'},
 {question:'Independent tests each have the same success probability. Count how many tests are needed until the first success.',choices:['Negative binomial, third-success stopping','Binomial, fixed trial count','Geometric waiting count'],answer:2,explanation:'The experiment stops at the first success. State whether the count includes the successful test.',topicId:'urv-b3-geometric'},
 {question:'Independent tests each have the same success probability. Count how many tests are needed until the third success.',choices:['Negative binomial waiting count','Poisson count','Hypergeometric count'],answer:0,explanation:'The trial count is random and the stopping target is a specified success number greater than one.',topicId:'urv-b4-negative-binomial'},
 {question:'Claims arrive through a constant-rate Poisson process. You need the number arriving over the next three months.',choices:['Exponential waiting time','Poisson count','Uniform amount'],answer:1,explanation:'The variable is an event count over a fixed exposure period. Convert the rate to that period.',topicId:'urv-b6-poisson'},
 {question:'Claims arrive through a constant-rate Poisson process. You need the time until the next claim.',choices:['Binomial count','Gamma with shape three','Exponential waiting time'],answer:2,explanation:'The variable is a continuous waiting time to one event. Its rate is the process rate.',topicId:'urv-c2-exponential'},
 {question:'Claims arrive through a constant-rate Poisson process. You need the time until the fourth claim.',choices:['Gamma waiting time with shape four','Poisson count with mean four','Geometric waiting count'],answer:0,explanation:'Four independent exponential waiting times add to a gamma waiting time with integer shape four.',topicId:'urv-c3-gamma'},
 {question:'A screen flags fraudulent and legitimate claims at different rates. Given that a claim was flagged, find its fraud probability.',choices:['Use sensitivity directly','Bayes with total flag probability','Treat fraud and flag as independent'],answer:1,explanation:'The requested condition reverses the supplied screening probabilities. Include flags from both groups in the denominator.',topicId:'f2-bayes-theorem'},
 {question:'Two independent normal amounts are compared. You need the probability X exceeds Y.',choices:['Use a CLT approximation for individual observations','Subtract their variances','Form the normal difference and standardize'],answer:2,explanation:'An independent normal combination is exactly normal. Its difference variance is the sum of the individual variances.',topicId:'mrv-e1-linear-combinations'},
 {question:'You need the probability that the maximum of six i.i.d. continuous losses is below a threshold.',choices:['Require all six below it, then multiply CDF values','Use the density at the threshold','Add the six CDF values'],answer:0,explanation:'The maximum is below the threshold exactly when every observation is below it.',topicId:'mrv-d1-order-statistics'},
 {question:'You need a tail probability for a total of 400 i.i.d. non-normal losses with finite positive variance. An approximation is requested.',choices:['Assume every individual loss is normal','CLT for the total, using SD times square root n','Use the individual SD for the total'],answer:1,explanation:'The CLT concerns the sum or mean, under the stated assumptions. Standardize the total using its mean and SD.',topicId:'mrv-f1-central-limit-theorem'},
 {question:'A loss is subject to an ordinary deductible and an insurer share. You need expected insurer payment per loss.',choices:['Apply the payment rule to mean loss','Condition on positive payment automatically','Apply the rule to each loss and average all payments'],answer:2,explanation:'The nonlinear payment rule must be applied before expectation. Per-loss expectation includes zero payments.',topicId:'urv-h3-moments-loss-payment'},
];
