import { seededRandom, uniformPaymentMoments, insurancePayment } from './lab-math.js';
import teaching from './content/teaching.js';
const choose = (n, k) => { if(k < 0 || k > n) return 0; let v = 1; for(let i = 1; i <= k; i++) v = v * (n - i + 1) / i; return v; };
const fmt = value => Number(value.toFixed(4)).toString();
function question(topicId, seed, text, value, wrong, explanation) {
  const options = [{ value, feedback: '' }];
  for (const [v, feedback] of wrong) if (Number.isFinite(v) && !options.some(o => fmt(o.value) === fmt(v))) options.push({ value: v, feedback });
  let bump = 1;
  while(options.length < 5) {
    const v = value + bump * Math.max(.0137, Math.abs(value) * .13); bump++;
    if(!options.some(o => fmt(o.value) === fmt(v))) options.push({ value: v, feedback: `This value does not follow the required calculation. ${teaching[topicId].trap}` });
  }
  const random = seededRandom(seed + 87);
  for(let i = options.length - 1; i > 0; i--) { const j = Math.floor(random() * (i + 1)); [options[i], options[j]] = [options[j], options[i]]; }
  return { id: `variant:${topicId}:${seed}`, learningId: `variant:${topicId}`, topicId, question: `${text} Round to four decimal places when needed.`,
    answer: options.findIndex(o => o.value === value), choices: options.map(o => `$${fmt(o.value)}$`),
    feedback: Object.fromEntries(options.map((o, i) => [i, o.feedback])), solution: explanation,
    hints: [teaching[topicId].method, teaching[topicId].setup], trap: teaching[topicId].trap, checkpoint: teaching[topicId].check,
    numericAnswer: value, seed, variant: true };
}
export function generateVariant(topicId, seed = Date.now() % 1000000) {
  const random = seededRandom(seed);
  const pick = list => list[Math.floor(random() * list.length)];
  const n = pick([4,5,6,7]), p = pick([.2,.3,.4]), c = pick([100,200,400]);
  const q = pick([.1,.15,.25]), both = p * q;
  const build = (text, value, wrong, explanation) => question(topicId, seed, text, value, wrong, explanation);
  const wrong = (values, message) => values.map(v => [v, message]);
  if(topicId === 'a1-set-functions') return build(`A set function assigns to a collection of claims the sum of their amounts. A collection contains claims of ${c}, ${2*c}, and ${3*c}. Calculate the set-function value.`,6*c,wrong([3*c, c, 1, 6], 'Add the amounts of all claims in the input collection; this function is not a probability.'),[`The function adds the claim amounts in the set.`,`${c}+${2*c}+${3*c}=${6*c}.`]);
  if(['a2-venn-diagrams','e1-addition-rule','b4-combinatorial-probability'].includes(topicId)) {
    if(topicId === 'b4-combinatorial-probability') return build(`Two files are selected uniformly without replacement from ${n} files, exactly two of which are flagged. Calculate the probability both selected files are flagged.`,1/choose(n,2),wrong([2/n,4/n**2,1/n,1/(n*(n-1))],'Count favorable and total unordered pairs consistently.'),[`There is one favorable pair and ${choose(n,2)} equally likely pairs.`,`Probability is 1/${choose(n,2)}=${fmt(1/choose(n,2))}.`]);
    return build(`P(A)=${p}, P(B)=${q}, and P(A intersection B)=${both}. Calculate P(A union B).`,p+q-both,[[p+q,'This adds the overlap twice; subtract the intersection.'],[both,'This is the intersection, not the union.'],[1-p-q+both,'This is the complement of the union.'],[p,'This omits outcomes in B outside A.']],[`The union counts each qualifying outcome once.`,`${p}+${q}-${both}=${fmt(p+q-both)}.`]);
  }
  if(topicId==='a3-sample-space') return build(`A complete outcome records whether each of ${n} labeled policies has a claim. Calculate the number of possible complete outcomes.`,2**n,wrong([n,2*n,n**2,2],'Each labeled policy has two possibilities; multiply across all labels.'),[`There are two possibilities per labeled policy.`,`The count is 2 raised to ${n}, or ${2**n}.`]);
  if(topicId==='a4-events') return build(`The probability of no claims is ${p}. Calculate the probability of at least one claim.`,1-p,[[p,'This is the complement of the event requested.'],[p**2,'No multiplication across trials is specified.'],[1,'At least one is not certain.'],[0,'The probability is positive.']],[`At least one claim is the complement of no claims.`,`1-${p}=${1-p}.`]);
  if(['a5-probability-set-function','a6-axioms-probability'].includes(topicId)) return build(`Three disjoint exhaustive events have probabilities ${p}, ${q}, and r. Calculate r.`,1-p-q,[[p+q,'That is the known mass, not the missing mass.'],[p*q,'Exhaustive disjoint events use addition, not independence.'],[1-p,'This leaves out the second known event.'],[1-q,'This leaves out the first known event.']],[`The disjoint event probabilities must sum to one.`,`r=1-${p}-${q}=${fmt(1-p-q)}.`]);
  if(topicId==='b1-counting-principles') return build(`A policy has ${n} deductible choices and three coverage choices. Every pairing is allowed. Calculate the number of policies.`,3*n,[[n+3,'These are stages of one construction; multiply rather than add.'],[n,'This counts only deductible choices.'],[3,'This counts only coverage choices.'],[n**3,'There are two choice stages, not three selections of a deductible.']],[`Each deductible can be paired with each of three coverage choices.`,`${n} times 3 = ${3*n}.`]);
  if(['b2-permutations','b3-combinations'].includes(topicId)) { const ordered = topicId==='b2-permutations'; return build(ordered?`A president and a treasurer are chosen from ${n} distinct people. One person cannot hold both roles. Calculate the number of assignments.`:`A two-person committee is selected from ${n} distinct people. Calculate the number of committees.`, ordered?n*(n-1):choose(n,2),[[ordered?choose(n,2):n*(n-1),ordered?'This ignores the two different roles.':'This counts each committee twice, once per order.'],[n**2,'This permits choosing the same person twice.'],[n,'This accounts for only one selection.'],[2*n,'The second selection has n-1 possibilities.']],[ordered?'The two roles are labeled, so order matters.':'Committee membership is unordered.',ordered?`${n} times ${n-1} = ${n*(n-1)}.`:`${n} times ${n-1} divided by 2 = ${choose(n,2)}.`]); }
  if(['c1-independent-events','e2-multiplication-rule'].includes(topicId)) return build(`P(A)=${p} and P(B given A)=${q}. Calculate P(A intersection B).`,both,[[p+q,'A joint event uses multiplication with a conditional factor, not addition.'],[q,'This omits the probability of reaching event A.'],[p,'This omits the conditional second factor.'],[p/q,'The multiplication rule multiplies rather than divides these factors.']],[`Use P(A) times P(B given A); independence is not needed.`,`${p} times ${q} = ${fmt(both)}.`]);
  if(topicId==='c2-independent-trials') return build(`Each of ${n} independent policies has claim probability ${p}. Calculate the probability at least one has a claim.`,1-(1-p)**n,[[ (1-p)**n,'This is the probability of no claims; take its complement.'],[p**n,'This is the probability all policies have claims.'],[1-p**n,'This is the probability not all have claims.'],[n*p,'This adds overlapping claim events and can exceed one.']],[`Use the complement: no claims means every policy avoids a claim.`,`1-(1-${p}) raised to ${n} = ${fmt(1-(1-p)**n)}.`]);
  if(topicId==='d1-mutually-exclusive') return build(`A and B are mutually exclusive, with probabilities ${p} and ${q}. Calculate P(A union B).`,p+q,[[p+q-p*q,'Disjoint events have zero intersection, not the independent product.'],[p*q,'This is an independence product, not a disjoint union.'],[p,'This omits B.'],[1-p-q,'This is the union complement.']],[`Disjoint events have no overlap.`,`${p}+${q}=${fmt(p+q)}.`]);
  if(['d2-partitions','f3-law-total-probability','e3-combined-problems'].includes(topicId)) {const t=p*.6+(1-p)*.1; return build(`A proportion ${p} of insureds are high risk with claim probability 0.6; the remaining insureds have claim probability 0.1. Calculate the overall claim probability.`,t,[[.35,'An unweighted average ignores unequal class shares.'],[.7,'Conditional rates cannot be added without their class weights.'],[p*.6,'This omits claims from low-risk insureds.'],[p,'This is the high-risk share, not the claim rate.']],[`The classes form a partition, so add their weighted claim contributions.`,`${p}(0.6)+(1-${p})(0.1)=${fmt(t)}.`]);}
  if(topicId==='f1-conditional-probability') return build(`P(A)=${p}, P(B)=0.5, and P(A intersection B)=${p/2}. Calculate P(A given B).`,p,[[.5,'This is P(B given A), reversing the condition.'],[p/2,'The joint mass must be divided by the condition probability.'],[p*.5,'Multiplication does not renormalize the condition.'],[1-p,'This is the complement of the requested probability.']],[`Given B, the denominator is P(B)=0.5.`,`${p/2}/0.5=${p}.`]);
  if(topicId==='f2-bayes-theorem') {const joint=p*.8,total=joint+(1-p)*.1; return build(`A proportion ${p} of claims are fraudulent. The screen flags 80% of fraudulent claims and 10% of legitimate claims. Given a flag, calculate the fraud probability.`,joint/total,[[.8,'This is sensitivity, P(flag given fraud), reversing the requested condition.'],[p,'This is the prior fraud share before observing a flag.'],[joint,'This is a joint probability; divide by all flagged claims.'],[total,'This is the total flag probability, the denominator.']],[`Count flags from both fraud and legitimate claims.`,`Fraud flags: 0.8(${p})=${fmt(joint)}. All flags: ${fmt(joint)}+0.1(1-${p})=${fmt(total)}.`,`Divide ${fmt(joint)} by ${fmt(total)} to obtain ${fmt(joint/total)}.`]);}
  if(['urv-a1-random-variables','urv-e1-expected-value','urv-h1-loss-variable'].includes(topicId)) return build(`Policy loss X is ${c} with probability ${p} and zero otherwise. Calculate E[X].`,p*c,[[c,'This is the positive severity, conditional on a loss, not the policy-level mean.'],[c/p,'Weight severity by the occurrence probability; do not divide.'],[(1-p)*c,'This uses the no-loss probability as the positive-loss weight.'],[p*c*c,'This is the second raw moment, not the mean.']],[`Average both possible outcomes using their probabilities.`,`E[X]=${c}(${p})+0(1-${p})=${fmt(p*c)}.`]);
  if(['urv-a2-pdf','urv-a3-cdf'].includes(topicId)) return build(`X has density f(x)=2x on (0,1) and zero elsewhere. Calculate P(X<=${p}).`,p*p,[[2*p,'This is density height, not probability area.'],[p,'This would apply to a uniform (0,1) variable.'],[1-p*p,'This is the upper tail.'],[p*p/2,'The density coefficient 2 cancels the integration divisor 2.']],[`Integrate the density from zero to the threshold.`,`F(x)=x squared on (0,1), so F(${p})=${fmt(p*p)}.`]);
  if(topicId==='urv-b1-discrete-uniform') return build(`X is uniform on the integers 1 through ${n}. Calculate E[X].`,(n+1)/2,[[n/2,'Both inclusive endpoints matter.'],[1/n,'This is the probability of one supported value.'],[n,'This is the maximum, not the average.'],[n*(n+1)/2,'This sums the values without their probability weights.']],[`Equal weights make the mean the midpoint of the supported endpoints.`,`(1+${n})/2=${(n+1)/2}.`]);
  if(topicId==='urv-b2-binomial') return build(`Exactly ${n} independent policies each have claim probability ${p}. Calculate the probability of exactly one claim.`,n*p*(1-p)**(n-1),[[p*(1-p)**(n-1),'This counts a specific successful policy; include n possible locations.'],[1-(1-p)**n,'This is at least one, not exactly one.'],[p**n,'This is all policies claiming.'],[(1-p)**n,'This is no claims.']],[`A fixed number of independent identical Bernoulli trials gives a binomial count.`,`Choose the successful policy in ${n} ways: ${n}(${p})(1-${p}) raised to ${n-1} = ${fmt(n*p*(1-p)**(n-1))}.`]);
  if(topicId==='urv-b3-geometric') return build(`Independent trials have success probability ${p}. Let T count trials including the first success. Calculate P(T=${n}).`,(1-p)**(n-1)*p,[[ (1-p)**n*p,'This counts n failures before success, so its trial count is n+1.'],[(1-p)**n,'This is survival past n trials.'],[p**n,'This requires every trial to be a success.'],[p,'Earlier failures still have to occur.']],[`The first ${n-1} trials must fail and trial ${n} must succeed.`,`(1-${p}) raised to ${n-1}, times ${p} = ${fmt((1-p)**(n-1)*p)}.`]);
  if(topicId==='urv-b4-negative-binomial') return build(`Independent trials have success probability ${p}. Let T be the trial number of the second success. Calculate P(T=${n}).`,(n-1)*p*p*(1-p)**(n-2),[[p*p*(1-p)**(n-2),'This counts only one position for the first success.'],[choose(n,2)*p*p*(1-p)**(n-2),'This is a fixed-n binomial count; the last trial must be the second success.'],[(1-p)**n,'This represents no successes.'],[p*p,'This omits failures and the position of the first success.']],[`The last trial succeeds; exactly one of the first ${n-1} trials succeeds.`,`${n-1}(${p}) squared, times (1-${p}) raised to ${n-2} = ${fmt((n-1)*p*p*(1-p)**(n-2))}.`]);
  if(topicId==='urv-b5-hypergeometric') return build(`Two files are selected uniformly without replacement from ${n} files, exactly two of which are fraudulent. Calculate the probability exactly one selected file is fraudulent.`,2*(n-2)/choose(n,2),[[2*(2/n)*(1-2/n),'This treats the draws as independent with replacement.'],[2/n,'This is the success probability of a single draw.'],[1/choose(n,2),'This is the probability both files are fraudulent.'],[(n-2)/choose(n,2),'This omits the two ways to choose the fraudulent file.']],[`Choose one of two fraudulent files and one of ${n-2} legitimate files.`,`Favorable pairs: 2(${n-2}); total pairs: ${choose(n,2)}. Probability = ${fmt(2*(n-2)/choose(n,2))}.`]);
  if(topicId==='urv-b6-poisson') {const rate=pick([2,3,4]);return build(`Claims follow a Poisson process at rate ${rate} per year. Calculate the probability of no claims over half a year.`,Math.exp(-rate/2),[[Math.exp(-rate),'This uses a full year of exposure.'],[rate/2,'This is the mean count, not the probability of zero.'],[1-Math.exp(-rate/2),'This is at least one claim.'],[Math.exp(-2*rate),'Half a year reduces rather than doubles the mean.']],[`The mean count is rate times exposure: ${rate}/2.`,`P(N=0)=exp(-${rate/2})=${fmt(Math.exp(-rate/2))}.`]);}
  if(topicId==='urv-c1-continuous-uniform') return build(`X is uniform on (0,${c}). Calculate P(X>${p*c}).`,1-p,[[p,'This is the lower tail.'],[1/c,'This is density height.'],[c-p*c,'Divide the interval length by total support length.'],[p*c,'This is the threshold, not its probability.']],[`Uniform probability is qualifying length divided by total length.`,`(${c}-${p*c})/${c}=${1-p}.`]);
  if(topicId==='urv-c2-exponential') return build(`Waiting time T is exponential with mean ${n}. Calculate P(T>${n*2}).`,Math.exp(-2),[[1-Math.exp(-2),'This is the lower tail.'],[Math.exp(-2*n*n),'The rate is reciprocal mean, not the mean itself.'],[.5,'Exponential survival is not a linear tail ratio.'],[2,'This is rate times time, which goes inside a negative exponential.']],[`Rate is 1/${n}; exponential survival is exp(-rate times time).`,`exp(-${2*n}/${n})=exp(-2)=${fmt(Math.exp(-2))}.`]);
  if(topicId==='urv-c3-gamma') return build(`X is gamma with shape ${n} and rate ${p}. Calculate E[X].`,n/p,[[n*p,'This treats the rate as a scale.'],[1/p,'This is the mean of one exponential waiting time, not shape n.'],[n/(p*p),'This is the gamma variance.'],[p/n,'The mean is shape divided by rate.']],[`For the rate convention, mean is shape divided by rate.`,`${n}/${p}=${fmt(n/p)}.`]);
  if(topicId==='urv-c4-beta') return build(`X is beta with shape parameters ${n} and 2. Calculate E[X].`,n/(n+2),[[n/2,'The denominator is the sum of both shapes.'],[2/(n+2),'This reverses the two shape roles.'],[(n-1)/n,'This is the interior mode for these shapes, not the mean.'],[n,'The mean must lie in (0,1).']],[`The beta mean is alpha/(alpha+beta).`,`${n}/(${n}+2)=${fmt(n/(n+2))}.`]);
  if(topicId==='urv-c5-normal') return build(`X is normal with mean ${c} and variance ${n*n}. Calculate the z-score at x=${c+2*n}.`,2,[[2/n,'This divides by variance rather than SD.'],[2*n,'This only subtracts the mean.'],[-2,'This reverses the subtraction order.'],[(c+2*n)/n,'This omits subtracting the mean.']],[`SD is the square root of variance, or ${n}.`,`z=(${c+2*n}-${c})/${n}=2.`]);
  if(topicId==='urv-c6-lognormal') return build(`log X is normal with mean 0 and variance ${p}. Calculate E[X].`,Math.exp(p/2),[[1,'exp(E[log X]) is the median, not the mean.'],[Math.exp(p),'The exponent uses half the variance.'],[p,'This is log variance, not mean X.'],[0,'X is positive with a positive mean.']],[`For a lognormal variable, mean is exp(mu+variance/2).`,`exp(${p}/2)=${fmt(Math.exp(p/2))}.`]);
  if(topicId==='urv-d1-conditional-discrete') return build(`X is uniform on the integers 1 through ${n}. Calculate P(X=${n} given X>=${n-2}).`,1/3,[[1/n,'This is the unconditional probability; restrict and renormalize.'],[3/n,'This is the probability of the condition.'],[1/2,'The retained support has three values, including both endpoints.'],[1,'The condition does not force the largest value.']],[`Given the condition, three equally likely values remain.`,`The maximum has conditional probability 1/3=${fmt(1/3)}.`]);
  if(topicId==='urv-d2-conditional-continuous') return build(`X is uniform on (0,${c}). Calculate P(X>${.6*c} given X>${.2*c}).`,.5,[[.4,'This is the unconditional upper-tail probability.'],[.8,'This is the denominator, the probability of the condition.'],[.32,'Conditional probability divides by the denominator rather than multiplying.'],[.6,'This is the lower-tail proportion of the higher threshold.']],[`The stricter tail is contained within the conditioning tail.`,`(${c} - ${.6*c}) / (${c} - ${.2*c}) = 0.5.`]);
  if(topicId==='urv-e3-mode-median-percentiles') return build(`X is uniform on (0,${c}). Calculate its ${100*p}th percentile.`,p*c,[[c/2,'This is the median, not the requested percentile.'],[p,'This is the cumulative probability, not its loss threshold.'],[(1-p)*c,'This uses the complementary percentile.'],[c,'This is the support endpoint.']],[`For this uniform model F(x)=x/${c}.`,`Solve x/${c}=${p}, so x=${fmt(p*c)}.`]);
  if(['urv-e2-moments','urv-f1-variance','urv-f2-standard-deviation','urv-f3-coefficient-variation'].includes(topicId)) {const mean=p*c,second=p*c*c,variance=p*(1-p)*c*c,sd=Math.sqrt(variance);const type=topicId==='urv-e2-moments'?'second raw moment':topicId==='urv-f1-variance'?'variance':topicId==='urv-f2-standard-deviation'?'standard deviation':'coefficient of variation';const answer={'second raw moment':second,variance,'standard deviation':sd,'coefficient of variation':sd/mean}[type];return build(`X equals ${c} with probability ${p} and zero otherwise. Calculate its ${type}.`,answer,wrong([mean,second,variance,sd,mean*mean,sd/mean].filter(v=>v!==answer).slice(0,4),`Keep mean, second raw moment, variance, SD, and CV distinct. The requested quantity is ${type}.`),[`E[X]=${fmt(mean)}, E[X squared]=${fmt(second)}; variance=${fmt(second)}-${fmt(mean*mean)}=${fmt(variance)}.`,`SD=${fmt(sd)}; CV=SD/mean=${fmt(sd/mean)}. The requested ${type} is ${fmt(answer)}.`]);}
  if(/^urv-[gh]/.test(topicId)) { const d=c,loss=4*c,share=.8,cap=2*c;
    if(topicId==='urv-g1-deductibles')return build(`An ordinary deductible is ${d} and the loss is ${loss}. Calculate insurer payment, with no other policy terms.`,loss-d,[[loss,'This ignores the deductible.'],[d,'This is the policyholder deductible, not insurer payment.'],[0,'The loss exceeds the deductible.'],[loss+d,'A deductible reduces rather than increases insurer payment.']],[`The positive excess is the covered loss.`,`max(${loss}-${d},0)=${loss-d}.`]);
    if(topicId==='urv-g2-coinsurance')return build(`The loss is ${loss}, ordinary deductible ${d}, and the policyholder pays 20% of the remaining loss. Calculate insurer payment.`,share*(loss-d),[[.2*(loss-d),'This is the policyholder share, not insurer payment.'],[share*loss-d,'This subtracts the deductible after coinsurance, reversing the contract order.'],[loss-d,'This omits the insurer share.'],[share*loss,'This omits the deductible.']],[`The insurer share is 80%; apply it after the deductible.`,`0.8(${loss}-${d})=${share*(loss-d)}.`]);
    if(topicId==='urv-g3-benefit-limits') return build(`Loss is ${loss}, ordinary deductible ${d}, insurer share 80%, and the final payment cap ${cap}. Calculate insurer payment.`,cap,[[share*(loss-d),'This is the uncapped payment; apply the final cap.'],[share*cap,'This places the cap before coinsurance, but it is on the final payment.'],[loss-d,'This omits coinsurance and the cap.'],[loss,'This omits all contract terms.']],[`First calculate 80% of the positive excess, then cap that payment.`,`min(0.8(${loss}-${d}),${cap})=${cap}.`]);
    if(topicId==='urv-g4-inflation') return build(`Original loss is ${loss}. Loss inflation is 25%; the ordinary deductible remains fixed at ${d}. There is no coinsurance or cap. Calculate insurer payment.`,1.25*loss-d,[[1.25*(loss-d),'This inflates the deductible too. It stays fixed in this contract.'],[loss-d,'This omits loss inflation.'],[1.25*loss,'This omits the deductible.'],[loss,'This is the original loss.']],[`Inflate the loss first; keep the deductible fixed.`,`1.25(${loss})-${d}=${1.25*loss-d}.`]);
    if(topicId==='urv-h2-payment-variable') return build(`X is uniform on (0,${4*c}). Payment is Y=max(X-${c},0). Calculate P(Y=0).`,.25,[[0,'A whole loss interval maps to zero; this is not a continuous point probability in X.'],[.75,'This is the probability of positive payment.'],[c,'This is the deductible, not its probability.'],[1/(4*c),'This is loss density height.']],[`Zero payment occurs when X is at or below the deductible.`,`${c}/${4*c}=0.25.`]);
    const m=uniformPaymentMoments(4*c,c,1,100000);return build(`X is uniform on (0,${4*c}). Payment is Y=max(X-${c},0). Calculate E[Y] per loss.`,m.mean,[[2*c-c,'Applying the payment rule to E[X] does not equal E[Y].'],[1.5*c,'This is the mean positive payment, conditioning on Y>0.'],[2*c,'This is the mean original loss.'],[3*c,'This is the maximum payment, not its mean.']],[`Include the zero-payment losses when averaging the payment rule.`,`Integrate (x-${c})/(${4*c}) from ${c} to ${4*c}. The result is (${3*c}) squared / (${8*c})=${fmt(m.mean)}.`]);
  }
  if(['mrv-a1-joint-distributions','mrv-a2-conditional-distributions','mrv-b1-joint-moments','mrv-b2-conditional-variance','mrv-c1-covariance'].includes(topicId)) {
    const a=pick([.1,.2]), b=pick([.2,.3]), cc=pick([.1,.2]), d=1-a-b-cc;
    const px=cc+d,py=b+d,conditional=d/py,cv=conditional*(1-conditional),cov=d-px*py;
    const target=topicId==='mrv-a1-joint-distributions'?px:topicId==='mrv-a2-conditional-distributions'?conditional:topicId==='mrv-b1-joint-moments'?d:topicId==='mrv-b2-conditional-variance'?cv:cov;
    const request=topicId==='mrv-a1-joint-distributions'?'P(X=1)':topicId==='mrv-a2-conditional-distributions'?'P(X=1 given Y=1)':topicId==='mrv-b1-joint-moments'?'E[XY]':topicId==='mrv-b2-conditional-variance'?'Var(X given Y=1)':'Cov(X,Y)';
    return build(`For binary X,Y, the joint probabilities at (0,0), (0,1), (1,0), (1,1) are ${fmt(a)}, ${fmt(b)}, ${fmt(cc)}, ${fmt(d)}. Calculate ${request}.`,target,wrong([px,py,d,conditional,cv,0,cov].filter(v=>v!==target).slice(0,4),`Use the joint table and the precise requested quantity ${request}. Marginal and conditional weights differ.`),[`Marginals: P(X=1)=${fmt(px)} and P(Y=1)=${fmt(py)}. Conditional success probability given Y=1 is ${fmt(d)}/${fmt(py)}=${fmt(conditional)}.`,`E[XY]=${fmt(d)}. Conditional variance is p(1-p)=${fmt(cv)}. Covariance is ${fmt(d)}-${fmt(px)}(${fmt(py)})=${fmt(cov)}. Thus ${request}=${fmt(target)}.`]);
  }
  if(topicId==='mrv-d1-order-statistics') return build(`${n} independent losses are uniform on (0,1). Calculate the probability their maximum is at most ${p}.`,p**n,[[p,'Every observation must meet the threshold, not just one.'],[1-p**n,'This is the probability the maximum exceeds the threshold.'],[(1-p)**n,'This is the probability the minimum exceeds the threshold.'],[n*p,'The required event is an intersection, not a sum of individual probabilities.']],[`The maximum is below the threshold only when all observations are below it.`,`${p} raised to ${n}=${fmt(p**n)}.`]);
  if(['mrv-e1-linear-combinations','mrv-e2-linear-moments'].includes(topicId)) return build(`Independent X,Y have variances ${n} and 3. Calculate Var(2X-3Y+${c}).`,4*n+27,[[2*n-9,'Square coefficients and add independent variance contributions.'],[4*n-27,'A negative coefficient still has a positive square.'],[4*n+27+c,'A constant shift adds no variance.'],[n+3,'This ignores the coefficients.']],[`Independent variances add after squaring the coefficients.`,`4(${n})+9(3)=${4*n+27}; the constant contributes zero variance.`]);
  if(topicId==='mrv-f1-central-limit-theorem') return build(`There are ${n*n} i.i.d. losses, each with SD ${c}. Calculate the SD of their sample mean.`,c/n,[[c*n,'This is SD of the total, not the mean.'],[c/(n*n),'Divide SD by square root sample size, not by sample size.'],[c,'Averaging independent losses reduces the SD.'],[c*c/(n*n),'This is variance of the sample mean.']],[`Variance of the sample mean is individual variance divided by sample size.`,`SD=${c}/sqrt(${n*n})=${c/n}.`]);
  throw new Error(`No variant for ${topicId}`);
}
